**Task**

In this assignment, you will use anomaly detection techniques to detect credit card fraud using this modified dataset originally from Kaggle.  Each row represents one credit card transaction.  This dataset has anonymized features, except for the amount of the transaction.  

Your stakeholder reports that they have found that about 0.4% of transactions are fraudulent, and 99.6% are valid.  

Your task will be to locate anomalous transactions in this data using KMeans and IsolationForest models  

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
filename = '/content/drive/MyDrive/Week2_data/Machine Learning Data Sets/credit_card.csv'
df = pd.read_csv(filename)
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 29 columns]

1. KMeans:
    Remember to scale your data.

In [4]:
from sklearn.preprocessing import StandardScaler

# First, standardize the data.
scaler = StandardScaler()
scaled_df = scaler.fit_transform(df)

# Convert the scaled data back into a dataframe.
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)

# Print the scaled dataframe.
print(scaled_df)

            V1        V2        V3        V4        V5        V6        V7  \
0    -0.726092 -0.270865  1.389980  0.762227 -0.236899  0.264052  0.285346   
1     0.949810 -0.013020 -0.647336  0.110710  0.102482 -0.155239 -0.009963   
2    -0.725138 -1.235035  0.733929  0.062810 -0.377373  1.293991  0.797185   
3    -0.467623 -0.356408  0.750937 -0.808030  0.042565  0.868121  0.283501   
4    -0.593701  0.452248  0.540940  0.079101 -0.295578 -0.018016  0.613062   
...        ...       ...       ...       ...       ...       ...       ...   
9995 -0.582254  0.822928  0.675781 -0.436159  0.339986 -0.211684  0.974073   
9996 -0.698262  0.165437  1.081422 -0.358389  0.680357 -1.081387  0.501505   
9997 -1.414777 -0.618350  1.992252 -1.944731 -0.344833 -0.355713 -0.631952   
9998  0.243406 -0.143847 -0.412310  0.410330  1.823885  3.221485 -0.476516   
9999  0.983163 -0.739865  0.058241 -0.449300 -0.925103 -0.067181 -0.895100   

            V8        V9       V10  ...       V20       V21    

Fit a KMeans model to create 3 clusters.  Please use a random state of 42 for your model

In [5]:
from sklearn.cluster import KMeans

# Create a KMeans model with 3 clusters and a random state of 42.
kmeans = KMeans(n_clusters=3, random_state=42)

# Fit the model to the scaled data.
kmeans.fit(scaled_df)

# Print the cluster labels for each data point.
print(kmeans.labels_)

# Print the centroids of each cluster.
print(kmeans.cluster_centers_)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[0 0 0 ... 1 2 1]
[[-0.06119561  0.05322554 -0.05061978 -0.09420518 -0.11824847 -0.24471477
   0.18512108 -0.0356982  -0.68030898  0.10818141 -0.47042577  0.99185734
  -0.83726647 -0.72820605  0.42154493 -0.21780778 -0.4836122  -0.18047596
   0.10261781  0.04121461  0.08462915  0.14268248 -0.04567203 -0.09513569
  -0.01349789 -0.18952808  0.0986316   0.01302422  0.00740864]
 [ 0.03249854 -0.0081095   0.19028816  0.15197237 -0.14099175 -0.14527669
  -0.05496933 -0.04263655  0.46376827 -0.0880422   0.34457241 -0.59300824
   0.51981554  0.46046062 -0.31020637  0.05886361  0.34555366  0.09005483
  -0.12956647 -0.05660812 -0.04425144 -0.00988856  0.02858709 -0.12567026
  -0.04293532  0.16310144 -0.06738985 -0.00771176 -0.00405024]
 [ 0.06215986 -0.22372693 -1.32401803 -0.76240046  1.83546053  2.5653022
  -0.5528523   0.55471884 -0.17160333  0.14761035 -0.31968363 -0.44965172
   0.21767464  0.11899387  0.29856731  0.69938716 -0.25560437  0.23204516
   0.52765312  0.25038998 -0.09178507 -0.69

**Use scipy.spatial.distance.cdist to create a matrix of distances between each data point and each cluster center**

In [6]:
from scipy.spatial.distance import cdist

# Get the cluster centers.
cluster_centers = kmeans.cluster_centers_

# Calculate the distances between each data point and each cluster center.
distances = cdist(scaled_df, cluster_centers, metric='euclidean')

# Print the distances matrix.
print(distances)

[[2.80468161 4.39326354 5.85721494]
 [2.42642963 3.68608746 5.07508117]
 [6.5426218  7.33737825 8.65600243]
 ...
 [7.25374437 6.4078623  8.24946223]
 [6.81346291 6.26852314 4.97246188]
 [4.88282778 3.67991041 5.7359755 ]]


**Define a list of the indices of the anomalous data using the threshold given by the stakeholder (99.6% valid)**

In [7]:
# Calculate the percentage of valid data points.
valid_data_percentage = 100 - 0.4

# Get the distances from the distances matrix.
distances = cdist(scaled_df, cluster_centers, metric='euclidean')

# Find the maximum distance for each data point.
max_distances = np.max(distances, axis=1)

# Calculate the threshold based on the valid data percentage.
threshold = np.percentile(max_distances, valid_data_percentage)

# Identify data points with distances greater than the threshold.
anomalous_indices = np.where(max_distances > threshold)[0]

# Print the list of anomalous data indices.
print(anomalous_indices)

[ 159 1376 1619 2156 2212 2439 2594 2654 2756 2911 2914 2917 2923 3443
 5303 5412 5413 5529 5674 5704 5764 5977 6489 6643 6672 7322 7338 7470
 7596 7597 8124 8163 8437 8442 8856 8939 8999 9071 9304 9326]


**2. Isolation Forest:**

In [8]:
from sklearn.ensemble import IsolationForest

# Define the contamination value based on the stakeholder's requirement.
contamination = 0.004

# Instantiate the Isolation Forest model with the specified contamination and random state.
iso_forest = IsolationForest(contamination=contamination, random_state=42)

# Fit the model to the scaled data.
iso_forest.fit(scaled_df)

# Print the indices of the anomalous data points.
outlier_index = iso_forest.predict(scaled_df)

# Print the number of anomalous data points.
print(np.count_nonzero(outlier_index == -1))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


40


In [9]:
# Identify the indices of anomalous data points.
anomalous_indices = np.where(outlier_index == -1)[0]

# Print the list of anomalous data indices.
print(anomalous_indices)

[ 159 1619 2156 2756 2858 2914 2917 2923 5303 5412 5413 5704 6311 6489
 6581 6595 6634 6643 6672 6757 6761 6798 6829 7338 7470 7596 7597 8124
 8163 8437 8442 8627 8645 8667 8670 8856 8999 9071 9304 9326]


**3. Compare the list of anomalies from KMeans and Isolation Forest.  **

In [11]:
# Get the anomalous indices from both models.
kmeans_anomalies = anomalous_indices
iso_forest_anomalies = np.where(outlier_index == -1)[0]

# Find the common anomalous indices between both models.
common_anomalies = np.intersect1d(kmeans_anomalies, iso_forest_anomalies)

# Find the unique anomalous indices for each model.
kmeans_unique = np.setdiff1d(kmeans_anomalies, common_anomalies)
iso_forest_unique = np.setdiff1d(iso_forest_anomalies, common_anomalies)

# Print the results.
print("Common anomalies:", common_anomalies)
print("KMeans unique anomalies:", kmeans_unique)
print("Isolation Forest unique anomalies:", iso_forest_unique)

Common anomalies: [ 159 1619 2156 2756 2858 2914 2917 2923 5303 5412 5413 5704 6311 6489
 6581 6595 6634 6643 6672 6757 6761 6798 6829 7338 7470 7596 7597 8124
 8163 8437 8442 8627 8645 8667 8670 8856 8999 9071 9304 9326]
KMeans unique anomalies: []
Isolation Forest unique anomalies: []


**Answer the following:**

    a. How many anomalies did the two approaches agree on?

In [12]:
# Get the number of common anomalies.
num_common_anomalies = len(common_anomalies)

# Print the result.
print(f"Both approaches agreed on {num_common_anomalies} anomalies.")

Both approaches agreed on 40 anomalies.


b. What percentage of the anomalies did the two approaches agree on?

In [13]:
# Calculate the percentage of agreed anomalies.
percentage_agreed = (num_common_anomalies / len(kmeans_anomalies)) * 100

# Print the result.
print(f"The two approaches agreed on {percentage_agreed:.2f}% of the anomalies.")

The two approaches agreed on 100.00% of the anomalies.
